# 9장 - 취소

- 코틀린 코루틴에서 아주 중요한 기능 중 하나는 바로 취소(cancellation)임.
- 중단 함수를 사용하는 몇몇 클래스와 라이브러리는 취소를 반드시 지원하고 있음.
- 코틀린 코루틴의 취소 방식은 아주 간단하고 편리하며 안전함.

## 기본적인 취소

- Job 인터페이스는 취소하게 하는 `cancel` 메서드를 가지고 있음.
- `cancel` 메서드를 호출하면 다음과 같은 효과를 가져올 수 있음.
    - 호출한 코루틴은 첫 번째 중단점에서 잡을 끝냄.
    - 잡이 자식을 가지고 있다면, 그들 또한 취소되지만 부모는 영향을 받지 않음.
    - 잡이 취소되면, 취소된 잡은 새로운 코루틴의 부모로 사용될 수 없음. 취소된 잡은 Cancelling 상태가 되었다가 Cancelled 상태로 바뀜.

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        repeat(1_000) { i ->
            delay(200)
            println("Printing $i")
        }
    }
    delay(1100)
    job.cancel()
    job.join()
    println("Cancelled success")
}

실행결과
Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Cancelled success
```

- `cancel`이 호출된 뒤 다음 작업을 진행하기 전에 취소 과정이 완료되는 걸 기다리기 위해서 `join`을 사용하는 것이 일반적임.
    - `join` 을 사용하지 않으면 race condition이 될 수 있음.
    - `join` 을 추가하여 코루틴이 취소를 마칠 때까지 증단되므로, race condition이 발생하지 않음.
- `cancelAndJoin` 확장함수를 제공함.
    - 이는 `cancel`과 `join`을 함께 호출하는 방법임.
- 팩토리 함수로 생성된 Job()도 같은 방법으로 취소됨.
    - 이는 잡에 따린 수많은 코루틴을 한번에 취소할 때 자주 사용됨.
        - 팩토리 함수로 생성된 Job은 부모 Job으로 사용되기 때문.

## 취소는 어떻게 작동하는가?

- 잡이 취소되면 Cancelling 상태로 바뀜.
- 상태가 바뀐 뒤 첫 번째 중단점에서 `CancelationException` 예외를 던짐.
- 예외는 `try-catch` 구문을 사용하여 잡을 수도 있지만, 다시 던지는 것이 좋음.

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            repeat(1_000) { i ->
                delay(200)
                println("Printing $i")
            }
        } catch (e: CancellationException) {
            println(e)
            throw e
        }
    }
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled success")
}

실행결과
Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@53908b12
Cancelled success
```

- 취소된 코루틴이 단지 멈추는 것이 아니라 내부적으로 예외를 사용해 취소되는 걸 명심해야함.

## 취소 중 코루틴을 한 번 더 호출하기

- `CancelationException` 을 잡고 코루틴은 모든 자원을 정리할 필요가 있는 한 계속해서 실행될 수 있음.
- 하지만 정리 과정중 중단은 허용하지 않음
    - Job은 이미 Cancelling 상태가 되었기 때문에 중단되거나 다른 코루틴을 시작하는 건 절대 불가능함.
        - 다른 코루틴을 실행하면 그냥 무시해버림.
        - 중단하려고 하면 `CancelationException` 을 던짐.

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            repeat(1_000) { i ->
                delay(200)
                println("Printing $i")
            }
        } finally {
            println("Finally")
            launch {  // 무시됨
                println("Will not be printed")
            }
            delay(1000) // 예외 발생
            println("Will not printed")
        }
    }
    delay(1100)
    job.cancelAndJoin()
    println("Cancelled success")
}

실행결과
Printing 0
Printing 1
Printing 2
Printing 3
Printing 4
Finally
Cancelled success
```

- 가끔씩 코루틴이 이미 취소되었을 때 중단 함수를 반드시 호출해야 하는 경우도 있음.
    - ex) 데이터베이스의 변경 사항을 롤백하는 경우
- 이런 경우 함수 콜을 `withContext(NonCancellable)` 로 포장하는 방법이 많이 사용됨.
    - 이는 코드 블록의 컨텍스트를 바꿈.

## invokeOnCompletion

- 자원을 해제하는데 자주 사용되는 또 다른 방법은 Job의 `invokeOnCompletion` 메서드를 호출하는 것임.
- 이는 잡이 Completed, Cancelled와 같은 마지막 사태에 도달했을 때 호출될 핸들러를 지정하는 역할을 함.

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        delay(1000)
    }
    job.invokeOnCompletion { exception ->
        println(exception?.message.toString())
        println("Finished")
    }
    delay(400)
}
```

- 핸들러의 파라미터인 exception의 예외 종류는 다음과 같음.
    - 잡이 예외 없이 끝나면 null이 됨.
        - 위 코드인 경우 예외나 취소가 없으므로 `exception?.message.toString()` 은 null임.
    - 코루틴이 취소되었으면, `CancellationException` 이 됨.
- 잡이 `invokeOnCompletion`이 호출되기 전에 완료되었으면, 핸들러는 죽시 호출됨.
    - `onCancelling`과 `invokeImmediately` 파라미터를 사용하면 핸들러의 동작 방식을 변경할 수도 있음.
        - onCancelling이 true라면 Cancelling 상태에서 호출됨. 디폴트 값은 false임
        - `invokeImmediately` : 코루틴이 이미 원하는 상태일 때 핸들러가 지정되었다면 핸들러를 즉시 호출할지 여부를 결정하는 파라미터임. 디폴트 값은 true임.

```kotlin
    job.invokeOnCompletion(invokeImmediately = true) { exception ->
        println(exception?.message.toString())
        println("Finished")
    }

// job.invokeOnCompletion(invokeImmediately = true)
// job.invokeOnCompletion(onCancelling = true)
```

- `invokeOnCompletion` 는 취소하는 중에 동기적으로 호출되며, 어떤 스레드에서 실행할지 결정할 수 없음.

## 중단될 수 없는 걸 중단하기

- 취소는 중단점에서 일어나기 때문에 중단점이 없으면 취소를 할 수 없음.
- 이런 상황을 만들어 보기 위해, `delay`대신 `Thread.sleep` 을 사용할 수 있는데, `Thread.sleep` 을 사용한 구현은 정말 나쁜 방식이므로, 현업에선 절대 사용해선 안됨.
- `yield` 는 코루틴을 중단하고 즉시 재실행함.
    - 중단점이 생겼기 때문에, 취소(또는 디스패처를 사용해 스레드를 바꾸는 일)를 포함해 중단(또는 재실행) 중에 필요한 모든 작업을 할 수 있는 기회가 주어짐.
- 중단이 가능하지 않으면서, CPU 집약적이거나 시간 집약적인 연산들이 중단 함수에 있다면 각 연산들 사이에 `yield`를 사용하는 것이 좋음.
- 잡의 상태를 추적하여 중단 가능함.
    - `isActive`
- Job이 액티브 상태가 아니면 `CancellationException` 을 던지는 `ensureActive` 함수도 있음.
- 일반적으로 `ensureActive` 가 좀더 가벼워서 더 선호되고 있음.

## 궁금

1. 98p. 레이스 컨디션이 일어난다고 하는데, 잡이 cancelling상태일 때 코루틴이 실행 가능한가..?
    1. 만약에 cancel 메서드가 없고 join만 있으면 repeat(1000)번을 다 할 때 까지 기다리는거 맞죠?
    2. cancel이 있으면 cancelling → cancelled를 기다린다?

답변 : cancelled 완전히 어느정도 시간이 필요하므로, join을 해야함.

2. 100p. 오타인듯? call이 아니라 cancel

4. 103p. delay에서 예외가 발생 안하는 이유?
답변 : cancelling 중인 코루틴에서 finally로 중단 함수를 호출하고 있음.

6. 106p. 코드 실행 결과는 뭘까요?
답변 : Job 팩토리로 생성한 잡은 어떤 코루틴과도 연관되지 않으므로, 프린팅이 0 ~ 1000 호출됨.

8. 107p. `yield` 사용 예시가 동기식을 비동기식으로 풀어주는 느낌..?
답변 : 많은 리소스를 사용하는 연산에 대해서 yield를 사용하므로, 코루틴 스위칭 같은 느낌으로 사용.

10. 중단될 수 없는 걸 중단하기 섹션은 무엇을 의미하는지 잘 모르겠어요!
답변 : 중단함수가 없는 코루틴을 중단하는 방법!
